{"uuid": "66a20f66-6f3c-4eff-9e50-9a47beb13a75", "counter": 7, "stdout": "\u001b[0;31mfatal: [192.168.2.100]: FAILED! => {\"changed\": false, \"commands\": \"ping ip 192.168.2.1\", \"msg\": \"Ping failed unexpectedly\", \"packet_loss\": \"100%\", \"packets_rx\": 0, \"packets_tx\": 5, \"rtt\": {}}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "ee0f48ee-8f1e-4595-8f9c-dbd0fabee0cd", "event": "runner_on_failed", "pid": 5656, "created": "2024-10-26T11:48:39.601674+00:00", "parent_uuid": "000c2958-fa70-de15-cdcc-000000000005", "event_data": {"playbook": "playbooks/ping.yaml", "playbook_uuid": "d9e19dfb-5fd1-49cc-8dfd-86fbc3544407", "play": "Gather information about the Cisco router", "play_uuid": "000c2958-fa70-de15-cdcc-000000000003", "play_pattern": "routers", "task": "Test reachability to 10.10.10.10 using default vrf", "task_uuid": "000c2958-fa70-de15-cdcc-000000000005", "task_action": "ios_ping", "resolved_action": "cisco.ios.ios_ping", "task_args": "", "task_path": "/root/python/Network/ansible/playbooks/ping.yaml:24", "host": "192.168.2.100", "remote_addr": "192.168.2.100", "res": {"commands": "ping ip 192.168.2.1", "packet_loss": "100%", "packets_rx": 0, "packets_tx": 5, "rtt": {}, "msg": "Ping failed unexpectedly", "invocation": {"module_args": {"dest": "192.168.2.1", "afi": "ip", "df_bit": false, "state": "present", "count": null, "source": null, "size": null, "ingress": null, "egress": null, "timeout": null, "vrf": null}}, "_ansible_no_log": false, "changed": false}, "start": "2024-10-26T11:48:25.856188+00:00", "end": "2024-10-26T11:48:39.601548+00:00", "duration": 13.74536, "ignore_errors": null, "event_loop": null, "uuid": "66a20f66-6f3c-4eff-9e50-9a47beb13a75"}}