{"event": "verbose", "uuid": "9b2eaa1e-82a0-43c3-b837-26759d7bee57", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/root/Network_App/ansible/playbooks/roles/ospf/tasks/main.yml': line 15, column 5, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "9ae6499a-49fb-46d6-947b-0bd3caf80190", "created": "2025-02-13T06:45:23.564780+00:00"}